export const SET_SHIP_TYPE = 'SET_SHIP_TYPE';
export const SET_SHIP_ORIENTATION = 'SET_SHIP_ORIENTATION';
export const ADD_SHIP = 'ADD_SHIP';
export const SHIP_ADDED = 'SHIP_ADDED';
export const SET_WAITING_STAGE = 'SET_WAITING_STAGE';
export const SET_MAX_PLAYERS = 'SET_MAX_PLAYERS';
